authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    path('registro/', views.registro_view, name='registro'),
    path('registro/create/', views.registro_create, name='registro_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/receita/nova/', views.criar_receita, name='criar_receita'),
    path('dashboard/receita/<int:id>/edit/', views.dashboard_receita_edit, name='dashboard_receita_edit'),
    path('dashboard/receita/delete/', views.dashboard_receita_delete, name='dashboard_receita_delete'),

]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('receitas.urls')),
    path('authors/', include('authors.urls')),
    ]

#esta é as configs de urls para imgs de usuarios e arquivos staticos
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authors/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    authors = models.OneToOneField(User, on_delete=models.CASCADE)  # ON_DELETE models.cascade quando vc deletar o usuario vc deleta o perfil
    bio = models.TextField(default='', blank=True)

authors/forms/login.py
from django import forms
from utils.django_forms import add_placeholder


class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], 'Digite seu nome de usuário')
        add_placeholder(self.fields['password'], 'Digite sua senha')

    username = forms.CharField(
        label='Usuário',
    )
    password = forms.CharField(
        label='Senha',
        widget=forms.PasswordInput(),
    )

authors/forms/receita_form.py
from django import forms
from receitas.models import receita
from utils.django_forms import add_attr
from utils.strings import is_positive_number
from collections import defaultdict
from django.core.exceptions import ValidationError


class AuthorsReceitaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._my_errors = defaultdict(list)

        add_attr(self.fields.get('preparation_steps'), 'class', 'span-2')

    class Meta:
        model = receita
        fields = 'title', 'description', 'preparation_time', \
            'preparation_time_unit', 'servings', 'servings_unit', \
            'preparation_steps', 'cover'
        widgets = {
            'cover': forms.FileInput(
                attrs={
                    'class': 'span-2'
                }
            ),
            'servings_unit': forms.Select(
                choices=(
                    ('Porções', 'Porções'),
                    ('Pedaços', 'Pedaços'),
                    ('Pessoas', 'Pessoas'),
                ),
            ),
            'preparation_time_unit': forms.Select(
                choices=(
                    ('Minutos', 'Minutos'),
                    ('Horas', 'Horas'),
                ),
            ),
        }
        labels = {
            'preparation_time_unit': 'Tempo de preparo (ex.: Minutos, Hora)',
            'cover': 'Imagem',
            'preparation_time': 'Tempo de preparo',
            'servings_unit': 'Tipos de porções',
            'servings': 'Quantidade de porções',
            'title': 'Titulo',
            'description': 'Descrição',
            'preparation_steps': 'Etapas de preparação',
        }

#  Tipo de validação
    def clean_preparation_time(self):
        field_name = 'preparation_time'
        field_value = self.cleaned_data.get(field_name)

        if not is_positive_number(field_value):
            self._my_errors[field_name].append('O número deve ser positivo.')

        return field_value

    def clean_servings(self):
        field_name = 'servings'
        field_value = self.cleaned_data.get(field_name)

        if not is_positive_number(field_value):
            self._my_errors[field_name].append('O número deve ser positivo.')

        return field_value

authors/forms/registro_form.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from utils.django_forms import add_placeholder, strong_password


class RegistroForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], 'Seu nome de usuário')
        add_placeholder(self.fields['email'], 'Digite seu e-mail')
        add_placeholder(self.fields['first_name'], 'Digite seu nome')
        add_placeholder(self.fields['last_name'], 'Digite seu Sobrenome')
        add_placeholder(self.fields['password'], 'Digite sua senha')
        add_placeholder(self.fields['password2'], 'Repita sua senha')

    username = forms.CharField(
        label='Usuário',
        help_text=(
            'O nome de usuário deve conter letras, números ou um desses @.+-_.'
            'O comprimento deve estar entre 4 e 150 caracteres.'
        ),
        error_messages={
            'required': 'Este campo não deve estar vazio',
            'min_length': 'O nome de usuário deve ter pelo menos 4 caracteres',
            'max_length': 'O nome de usuário deve ter menos de 150 caracteres',
        },
        min_length=4, max_length=150,
    )
    first_name = forms.CharField(
        error_messages={'required': 'Digite seu Nome'},
        label='Nome'
    )
    last_name = forms.CharField(
        error_messages={'required': 'Digite seu Sobrenome'},
        label='Sobrenome'
    )
    email = forms.EmailField(
        error_messages={'required': 'O e-mail é obrigatório'},
        label='E-mail',
        help_text='Digite um E-mail valido.',
    )
    password = forms.CharField(
        widget=forms.PasswordInput(),
        error_messages={
            'required': 'A senha não deve estar vazia'
        },
        help_text=(
           'A senha deve ter pelo menos uma letra maiúscula, '
           'uma letra minúscula e um número. O comprimento deve ser '
           'pelo menos 8 caracteres.'
        ),
        validators=[strong_password],
        label='Senha'
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(),
        label='Confirme sua senha',
        error_messages={
            'required': 'Por favor, repita sua senha'
        },
    )

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
        ]

    def clean_email(self):
        email = self.cleaned_data.get('email', '')
        exists = User.objects.filter(email=email).exists()

        if exists:
            raise ValidationError(
                'O e-mail do usuário já está em uso', code='invalid',
            )

        return email

    def clean(self):
        cleaned_data = super().clean()

        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if password != password2:
            password_confirmation_error = ValidationError(
                'Senhas devem ser iguais',
                code='invalid'
            )
            raise ValidationError({
                'password': password_confirmation_error,
                'password2': [
                    password_confirmation_error,
                ],
            })

authors/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm, RegistroForm, AuthorsReceitaForm
from django.http import Http404
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from receitas.models import receita


# pagina de registro/formulario
def registro_view(request):
    registro_form_data = request.session.get('registro_form_data', None)
    form = RegistroForm(registro_form_data)
    return render(request, 'authors/pages/registro_view.html', {
        'form': form,
        'form_action': reverse('authors:registro_create'),
    })


# def para pagina de criaçao de cadastro/salvando os dados na base.
def registro_create(request):
    if not request.POST:
        raise Http404()

    POST = request.POST
    request.session['registro_form_data'] = POST
    form = RegistroForm(POST)

    if form.is_valid():
        user = form.save(commit=False)  # aqui está salvando a senha em uma variavel, pois nao foi para a base de dados
        user.set_password(user.password)  # aqui está criptografando a senha
        user.save()  # aqui está salvando a senha na base de dados
        messages.success(request, 'Seu Usuario foi criado com sucesso, por favor faça Seu Login.')

        del(request.session['registro_form_data'])
        return redirect(reverse('authors:login'))

    return redirect('authors:registro')


# pagina de login e senha
def login_view(request):
    form = LoginForm()
    return render(request, 'authors/pages/login.html', {
        'form': form,
        'form_action': reverse('authors:login_create'),
    })


# pagina para logar seu usuario valido com senha
def login_create(request):
    if not request.POST:
        raise Http404()

    form = LoginForm(request.POST)

    if form.is_valid():
        authenticated_user = authenticate(
            username=form.cleaned_data.get('username', ''),
            password=form.cleaned_data.get('password', ''),
        )

        if authenticated_user is not None:
            messages.success(request, 'Você está logado.')
            login(request, authenticated_user)
        else:
            messages.error(request, 'nome de usuário ou senha inválidos')
    else:
        messages.error(request, 'Dados Invalidos')

    return redirect(reverse('authors:dashboard'))


@login_required(login_url='authors:login', redirect_field_name='next')
def logout_view(request):
    if not request.POST:
        return redirect(reverse('authors:login'))

    if request.POST.get('username') != request.user.username:
        return redirect(reverse('authors:login'))

    logout(request)
    return redirect(reverse('authors:login'))


# entrando na dashboard ja logodo com seu usuario
@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard(request):
    receitas = receita.objects.filter(
        is_published=False,
        author=request.user,
    )
    return render(request, 'authors/pages/dashboard.html', {
        'receitas': receitas,
    })


# editando receitas
@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard_receita_edit(request, id):
    receitas = receita.objects.filter(
        is_published=False,
        author=request.user,
        pk=id,
    ).first()

    if not receitas:
        raise Http404

    form = AuthorsReceitaForm(
        # dados de texto/objetos vai em request.POST
        data=request.POST or None,
        # files recebe arquivos binarios ou seja arquivos que nao estao em formato de texto.
        files=request.FILES or None,
        instance=receitas)

    if form.is_valid():
        # Agora, o form é valido e eu posso tentar salvar
        receitas = form.save(commit=False)

        receitas.author = request.user
        receitas.preparation_steps_is_html = False
        receitas.is_published = False

        receitas.save()

        messages.success(request, 'Sua receita foi salva com sucesso!')
        return redirect(reverse('authors:dashboard_receita_edit',))

    return render(request, 'authors/pages/dashboard_receita.html', {
        'form': form
    })


# NOVA RECEITA
@login_required(login_url='authors:login', redirect_field_name='next')
def criar_receita(request):
    form = AuthorsReceitaForm(
        request.POST or None,
        files=request.FILES or None,
    )

    if form.is_valid():
        receitas: receita = form.save(commit=False)

        receitas.author = request.user
        receitas.preparation_steps_is_html = False
        receitas.is_published = False

        receitas.save()

        messages.success(request, 'Salvo com sucesso!')
        return redirect(
            reverse('authors:dashboard')
        )

    return render(
        request,
        'authors/pages/dashboard_receita.html',
        context={
            'form': form,
            'form_action': reverse('authors:criar_receita')
        }
    )


# Delete de receitas
@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard_receita_delete(request):
    if not request.POST:
        raise Http404

    POST = request.POST
    id = POST.get('id')

    receitas = receita.objects.filter(
        is_published=False,
        author=request.user,
        pk=id,
    ).first()

    if not receitas:
        raise Http404()

    receitas.delete()
    messages.success(request, 'Receita Deletada com sucesso!')
    return redirect(reverse('authors:dashboard'))

authors/templates/authors/pages/dashboard.html
<style>
    :root {
        --color-primary: #269fe6;
        --color-primary-hover: #2086c2;
        --color-primary-dark: #13141f;
        --color-primary-dark-hover: #212336;
        --color-primary-light: #d4ecfa;
        --color-primary-light-hover: #bdd8e7;
    
        --color-white: #fff;
        --color-black: #000;
    
        --color-dark-text: #444;
        --color-info-light: #cce5ff;
        --color-debug-light: #cce5ff;
        --color-success-light: #d4edda;
        --color-alert-light: #fff3cd;
        --color-warning-light: #fff3cd;
        --color-error-light: #f8d7da;
    
        --color-info-dark: #4d86c4;
        --color-debug-dark: #4d86c4;
        --color-success-dark: #4a9c5d;
        --color-alert-dark: #927f40;
        --color-warning-dark: #927f40;
        --color-error-dark: #da525d;
    
        --color-gray-0: #f9f9f9;
        --color-gray-1: #e0e0e0;
        --color-gray-2: #c7c7c7;
        --color-gray-3: #aeaeae;
        --color-gray-4: #959595;
        --color-gray-5: #7d7d7d;
        --color-gray-6: #646464;
        --color-gray-7: #4b4b4b;
        --color-gray-8: #323232;
        --color-gray-9: #191919;
    
        --font-primary: sans-serif;
        --font-headings: 'Roboto Slab', serif;
    
        --spacing-gutter-medium: 3rem;
        --spacing-gutter-large: 4rem;
    }

.authors-dashboard-container {
    max-width: 64rem;
    text-align: left;
    padding: var(--spacing-gutter-medium);
    margin: 0 auto;
}

.authors-dashboard-container h3,
.authors-dashboard-container p,
.authors-dashboard-container ul {
    list-style-type: none;
    margin: 1rem 0;
}

.del1 {
    padding: .7 .7rem;
    margin: .1rem;
    border-radius: 1rem;
    color: red;
    background-color: var(--color-gray-2);
}
.del{
    display: inline;
}

</style>

{% include 'receitas/partials/head.html' %}

<body>
    {%include 'authors/partials/menu.html'%}
    {%include 'receitas/partials/header.html'%}
    {%include 'receitas/partials/search.html'%}
    {%include 'receitas/partials/mensagem.html'%}
    <div class="main-content center container">
        <h2>Usuário ({{user}})</h2>
        {% include "authors/partials/login_mensagem.html" %}

        <div class="authors-dashboard-container">
            <h3>Suas receitas não publicadas</h3>

            <ul>
                {% for receita in receitas  %}
                <li>
                    <a href="{% url "authors:dashboard_receita_edit" receita.id %}">{{receita.title}}</a> -
                    <form class='del form-delete' action="{% url "authors:dashboard_receita_delete"%}" method='POST'>
                        {% csrf_token %}
                        <input type="hidden" name="id" value='{{receita.id}}'>
                        <button class='del1' type="submit">Delete</button>
                    </form>
                </li>
                {%empty%}
                    <li>
                        <p>
                            Você não tem nenhuma receita criada,
                            <a href="{% url 'authors:criar_receita' %}">Criar receitas</a>.
                        </p>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{%include 'receitas/partials/footer.html'%}
</body>
<script>
    function my_scope() {
        const forms = document.querySelectorAll('.form-delete');
         
        for (const form of forms) {
            form.addEventListener('submit', function (e) {
            e.preventDefault();
          
            const confirmed = confirm('Tem certeza que deseja deletar?');
          
            if (confirmed) {
                form.submit();
            }
            });
        }
        } 
        my_scope();
</script>


authors/templates/authors/pages/dashboard_receita.html
<style>
    :root {
        --color-primary: #269fe6;
        --color-primary-hover: #2086c2;
        --color-primary-dark: #13141f;
        --color-primary-dark-hover: #212336;
        --color-primary-light: #d4ecfa;
        --color-primary-light-hover: #bdd8e7;
    
        --color-white: #fff;
        --color-black: #000;
    
        --color-dark-text: #444;
        --color-info-light: #cce5ff;
        --color-debug-light: #cce5ff;
        --color-success-light: #d4edda;
        --color-alert-light: #fff3cd;
        --color-warning-light: #fff3cd;
        --color-error-light: #f8d7da;
    
        --color-info-dark: #4d86c4;
        --color-debug-dark: #4d86c4;
        --color-success-dark: #4a9c5d;
        --color-alert-dark: #927f40;
        --color-warning-dark: #927f40;
        --color-error-dark: #da525d;
    
        --color-gray-0: #f9f9f9;
        --color-gray-1: #e0e0e0;
        --color-gray-2: #c7c7c7;
        --color-gray-3: #aeaeae;
        --color-gray-4: #959595;
        --color-gray-5: #7d7d7d;
        --color-gray-6: #646464;
        --color-gray-7: #4b4b4b;
        --color-gray-8: #323232;
        --color-gray-9: #191919;
    
        --font-primary: sans-serif;
        --font-headings: 'Roboto Slab', serif;
    
        --spacing-gutter-medium: 3rem;
        --spacing-gutter-large: 4rem;
    }

    .authors-dashboard-container {
        max-width: 64rem;
        text-align: left;
        padding: var(--spacing-gutter-medium);
        margin: 0 auto;
    }

    .authors-dashboard-container h3,
    .authors-dashboard-container p,
    .authors-dashboard-container ul {
        list-style-type: none;
        margin: 1rem 0;
    }

    .left {
        text-align: left;
    }

</style>

{% include 'receitas/partials/head.html' %}

<body>
    {%include 'authors/partials/menu.html'%}
    {%include 'receitas/partials/header.html'%}
    {%include 'receitas/partials/search.html'%}
    {%include 'receitas/partials/mensagem.html'%}
    <div class="main-content center container">
        <h2>Usuário ({{user}})</h2>
        {% include "authors/partials/login_mensagem.html" %}
        <div class="left">
            {% include "authors/partials/forms.html" %}
        </div>    
    </div>
     

    {%include 'receitas/partials/footer.html'%}
</body>

authors/templates/authors/pages/login.html
<style>
    :root {
        --color-primary: #269fe6;
        --color-primary-hover: #2086c2;
        --color-primary-dark: #13141f;
        --color-primary-dark-hover: #212336;
        --color-primary-light: #d4ecfa;
        --color-primary-light-hover: #bdd8e7;
    
        --color-white: #fff;
        --color-black: #000;
    
        --color-dark-text: #444;
        --color-info-light: #cce5ff;
        --color-debug-light: #cce5ff;
        --color-success-light: #d4edda;
        --color-alert-light: #fff3cd;
        --color-warning-light: #fff3cd;
        --color-error-light: #f8d7da;
    
        --color-info-dark: #4d86c4;
        --color-debug-dark: #4d86c4;
        --color-success-dark: #4a9c5d;
        --color-alert-dark: #927f40;
        --color-warning-dark: #927f40;
        --color-error-dark: #da525d;
    
        --color-gray-0: #f9f9f9;
        --color-gray-1: #e0e0e0;
        --color-gray-2: #c7c7c7;
        --color-gray-3: #aeaeae;
        --color-gray-4: #959595;
        --color-gray-5: #7d7d7d;
        --color-gray-6: #646464;
        --color-gray-7: #4b4b4b;
        --color-gray-8: #323232;
        --color-gray-9: #191919;
    
        --font-primary: sans-serif;
        --font-headings: 'Roboto Slab', serif;
    
        --spacing-gutter-medium: 3rem;
        --spacing-gutter-large: 4rem;
    }
    
/* Forms */
.form-content {
    max-width: 64rem;
    margin: 0 auto;
    margin-bottom: var(--spacing-gutter-medium);
}
    
.form-content label,
.form-content .help-text,
.errorlist {
    display: block;
    margin: 0.5rem 0;
    font-size: 1.4rem;
    list-style-type: none;
}
    
.errorlist {
    color: var(--color-error-dark);
}
    
.form-content input {
    width: 100%;
    padding: 1rem;
    border-radius: 0.4rem;
    border: 1px solid var(--color-primary-dark);
}
    
.form-content-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(30rem, 1fr));
    gap: calc(var(--spacing-gutter-medium) / 2) var(--spacing-gutter-medium);
}
    
.form-content button {
    padding: 1rem 2rem;
    border: none;
    background: var(--color-primary-dark);
    color: var(--color-white);
}
    
@media (max-width: 600px) {
    .form-content-grid {
    grid-template-columns: repeat(auto-fit, minmax(100%, 1fr));
    }
}
    
.inline-form {
    display: inline;
    }
      
.plaintext-button {
    display: inline;
    border: none;
    background: none;
    cursor: pointer;
    color: var(--color-primary);
    font-size: 1.6rem;
}
</style>

{% include 'receitas/partials/head.html' %}

<body>
    {%include 'authors/partials/menu.html'%}
    {%include 'receitas/partials/header.html'%}
    {%include 'receitas/partials/search.html'%}
    {%include 'receitas/partials/mensagem.html'%}
    <div class="main-content center container">
        <h2>Login</h2>
        {% include "authors/partials/login_mensagem.html" %}
    </div>
    {% if not user.is_authenticated %}
        <div class='main-content container'>
            <form action="{{ form_action }}" method="POST">
                    {% csrf_token %}

                <div class='form-content form-content-grid'>
                    {% for field in form %}
                    <div class="form-group">
                        <label for="{{field.id_for_label}}">{{field.label}}</label>
                        {{field}}

                        {% if field.help_text %}
                        <p class='help-text'>{{field.help_text}}</p>
                        {% endif %}

                        {{field.errors}}
                    </div>
                    {% endfor %}
                </div>

                <div class='form-content form-content-grid'>
                    <div class="form-group">
                        <button type="submit">Enviar</button>
                    </div>
                </div>
            </form>
        </div>
    {% endif %}
    {%include 'receitas/partials/footer.html'%}
</body>

authors/templates/authors/pages/registro_view.html
<style>
    :root {
        --color-primary: #269fe6;
        --color-primary-hover: #2086c2;
        --color-primary-dark: #13141f;
        --color-primary-dark-hover: #212336;
        --color-primary-light: #d4ecfa;
        --color-primary-light-hover: #bdd8e7;

        --color-white: #fff;
        --color-black: #000;

        --color-dark-text: #444;
        --color-info-light: #cce5ff;
        --color-debug-light: #cce5ff;
        --color-success-light: #d4edda;
        --color-alert-light: #fff3cd;
        --color-warning-light: #fff3cd;
        --color-error-light: #f8d7da;

        --color-info-dark: #4d86c4;
        --color-debug-dark: #4d86c4;
        --color-success-dark: #4a9c5d;
        --color-alert-dark: #927f40;
        --color-warning-dark: #927f40;
        --color-error-dark: #da525d;

        --color-gray-0: #f9f9f9;
        --color-gray-1: #e0e0e0;
        --color-gray-2: #c7c7c7;
        --color-gray-3: #aeaeae;
        --color-gray-4: #959595;
        --color-gray-5: #7d7d7d;
        --color-gray-6: #646464;
        --color-gray-7: #4b4b4b;
        --color-gray-8: #323232;
        --color-gray-9: #191919;

        --font-primary: sans-serif;
        --font-headings: 'Roboto Slab', serif;

        --spacing-gutter-medium: 3rem;
        --spacing-gutter-large: 4rem;
    }

    /* Forms */
.form-content {
    max-width: 64rem;
    margin: 0 auto;
    margin-bottom: var(--spacing-gutter-medium);
}

.form-content label,
.form-content .help-text,
.errorlist {
    display: block;
    margin: 0.5rem 0;
    font-size: 1.4rem;
    list-style-type: none;
}

.errorlist {
    color: var(--color-error-dark);
}

.form-content input {
    width: 100%;
    padding: 1rem;
    border-radius: 0.4rem;
    border: 1px solid var(--color-primary-dark);
}

.form-content-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(30rem, 1fr));
    gap: calc(var(--spacing-gutter-medium) / 2) var(--spacing-gutter-medium);
}

.form-content button {
    padding: 1rem 2rem;
    border: none;
    background: var(--color-primary-dark);
    color: var(--color-white);
}

@media (max-width: 600px) {
.form-content-grid {
    grid-template-columns: repeat(auto-fit, minmax(100%, 1fr));
    }
}
</style>

{% include 'receitas/partials/head.html' %}

<body>
    {%include 'authors/partials/menu.html'%}
    {%include 'receitas/partials/header.html'%}
    {%include 'receitas/partials/search.html'%}
    {%include 'receitas/partials/mensagem.html'%}
    <div class='main-content center container'>
        <h2>CADASTRO</h2>
    </div>

    <div class='main-content container'>
        <form action="{{ form_action }}" method="POST">
                {% csrf_token %}

            <div class='form-content form-content-grid'>
                {% for field in form %}
                <div class="form-group">
                    <label for="{{field.id_for_label}}">{{field.label}}</label>
                    {{field}}

                    {% if field.help_text %}
                    <p class='help-text'>{{field.help_text}}</p>
                    {% endif %}

                    {{field.errors}}
                </div>
                {% endfor %}
            </div>

            <div class='form-content form-content-grid'>
                <div class="form-group">
                    <button type="submit">Enviar</button>
                </div>
            </div>
        </form>
    </div>

    {%include 'receitas/partials/footer.html'%}
</body>